; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:host]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<host/> +<shared.cpp> -<host/test.cpp>
upload_port = COM5
lib_deps = 
	hijelhub/HijelHID_BLEKeyboard@^0.4.1
	; h2zero/NimBLE-Arduino@^2.4.0
	adafruit/Adafruit SSD1306@^2.5.16

[env:client]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<client/> +<shared.cpp> -<client/test.cpp>
upload_port = COM6
lib_deps = 
	h2zero/NimBLE-Arduino@^2.4.0

[env:client2]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<client/> +<shared.cpp> -<client/test.cpp>
upload_port = COM12
lib_deps = 
	h2zero/NimBLE-Arduino@^2.4.0

[env:display]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<display/> +<shared.cpp>
upload_port = COM5
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.16
